//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost
    {
        public cost()
        {
            this.proj_cost = new HashSet<proj_cost>();
        }
    
        public int cost_id { get; set; }
        public string cost_name { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual ICollection<proj_cost> proj_cost { get; set; }
    }
}
