//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday_schedule
    {
        public int holiday_sched_id { get; set; }
        public string holiday_name { get; set; }
        public System.DateTime holiday_start_date { get; set; }
        public System.DateTime holiday_end_date { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
    }
}
