//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_severity
    {
        public issue_severity()
        {
            this.proj_issues = new HashSet<proj_issues>();
        }
    
        public int issue_severity_id { get; set; }
        public string issue_severity_desc { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual ICollection<proj_issues> proj_issues { get; set; }
    }
}
