//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_activity
    {
        public proj_activity()
        {
            this.proj_activity_resource = new HashSet<proj_activity_resource>();
        }
    
        public int proj_activity_id { get; set; }
        public int proj_wbs_id { get; set; }
        public string proj_activity_desc { get; set; }
        public System.DateTime proj_activity_start_date { get; set; }
        public Nullable<System.DateTime> proj_activity_end_date { get; set; }
        public Nullable<int> sequence { get; set; }
        public Nullable<int> predecessor { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string notes { get; set; }
        public int Duration_Days { get; set; }
    
        public virtual proj_wbs proj_wbs { get; set; }
        public virtual ICollection<proj_activity_resource> proj_activity_resource { get; set; }
    }
}
