//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_wbs
    {
        public proj_wbs()
        {
            this.proj_activity = new HashSet<proj_activity>();
        }
    
        public int proj_wbs_id { get; set; }
        public int proj_info_id { get; set; }
        public string proj_wbs_desc { get; set; }
        public System.DateTime proj_wbs_start_date { get; set; }
        public Nullable<System.DateTime> proj_wbs_end_date { get; set; }
        public int sequence { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string notes { get; set; }
        public string hurdle { get; set; }
    
        public virtual ICollection<proj_activity> proj_activity { get; set; }
        public virtual proj_info proj_info { get; set; }
    }
}
