//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_issues
    {
        public int proj_issue_id { get; set; }
        public int proj_info_id { get; set; }
        public int issue_type_id { get; set; }
        public string comments { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public int issue_severity_id { get; set; }
    
        public virtual issue_severity issue_severity { get; set; }
        public virtual issue_type issue_type { get; set; }
        public virtual proj_info proj_info { get; set; }
    }
}
