//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_sponsor
    {
        public proj_sponsor()
        {
            this.proj_info = new HashSet<proj_info>();
        }
    
        public int proj_sponsor_id { get; set; }
        public string proj_sponsor_first_name { get; set; }
        public string proj_sponsor_last_name { get; set; }
        public string proj_sponsor_phone { get; set; }
        public Nullable<int> proj_sponsor_gm_ext { get; set; }
        public string proj_sponsor_email { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string full_name { get; set; }
    
        public virtual ICollection<proj_info> proj_info { get; set; }
    }
}
