//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_log_code
    {
        public proj_log_code()
        {
            this.proj_log = new HashSet<proj_log>();
        }
    
        public int proj_log_code_id { get; set; }
        public string proj_log_code_desc { get; set; }
        public bool is_auto { get; set; }
        public bool is_comments_required { get; set; }
        public bool is_active { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual ICollection<proj_log> proj_log { get; set; }
    }
}
