//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_stakeholder
    {
        public int proj_stakeholder_id { get; set; }
        public int proj_info_id { get; set; }
        public int stakeholder_id { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual proj_info proj_info { get; set; }
        public virtual stakeholder stakeholder { get; set; }
    }
}
