//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_activity_resource
    {
        public int proj_activity_resource_id { get; set; }
        public int proj_activitiy_id { get; set; }
        public int resource_id { get; set; }
        public Nullable<decimal> resource_avail_pct { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string notes { get; set; }
    
        public virtual proj_activity proj_activity { get; set; }
        public virtual resource resource { get; set; }
    }
}
