//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource
    {
        public resource()
        {
            this.proj_activity_resource = new HashSet<proj_activity_resource>();
            this.resource_avail = new HashSet<resource_avail>();
        }
    
        public int resource_id { get; set; }
        public string resource_first_name { get; set; }
        public string resource_last_name { get; set; }
        public string resource_phone { get; set; }
        public Nullable<int> resource_gm_ext { get; set; }
        public string resource_email { get; set; }
        public string notes { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<int> resource_full_name { get; set; }
    
        public virtual ICollection<proj_activity_resource> proj_activity_resource { get; set; }
        public virtual ICollection<resource_avail> resource_avail { get; set; }
    }
}
