//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource_avail
    {
        public int resource_avail_id { get; set; }
        public System.DateTime unavail_start_date { get; set; }
        public System.DateTime unavail_end_date { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public int resource_id { get; set; }
        public int unavail_type_id { get; set; }
    
        public virtual resource resource { get; set; }
        public virtual unavail_type unavail_type { get; set; }
    }
}
