//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class risk_register
    {
        public int risk_reg_id { get; set; }
        public int proj_info_id { get; set; }
        public int risk_status_id { get; set; }
        public int risk_category_id { get; set; }
        public string @event { get; set; }
        public string cause { get; set; }
        public string effect { get; set; }
        public string threat_or_opportunity { get; set; }
        public int risk_objective_id { get; set; }
        public int risk_probability_id { get; set; }
        public int risk_impact_id { get; set; }
        public string response_action { get; set; }
        public string responsible_person { get; set; }
        public string interval_check { get; set; }
        public string notes { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public int response_type_id { get; set; }
    
        public virtual proj_info proj_info { get; set; }
        public virtual response_type response_type { get; set; }
        public virtual risk_category risk_category { get; set; }
        public virtual risk_impact risk_impact { get; set; }
        public virtual risk_objective risk_objective { get; set; }
        public virtual risk_probability risk_probability { get; set; }
        public virtual risk_status risk_status { get; set; }
    }
}
