//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class stakeholder
    {
        public stakeholder()
        {
            this.proj_stakeholder = new HashSet<proj_stakeholder>();
        }
    
        public int stakeholder_id { get; set; }
        public string stakeholder_first_name { get; set; }
        public string stakeholder_last_name { get; set; }
        public string stakeholder_phone { get; set; }
        public Nullable<int> stakeholder_gm_ext { get; set; }
        public string stakeholder_email { get; set; }
        public string notes { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string stakeholder_full_name { get; set; }
    
        public virtual ICollection<proj_stakeholder> proj_stakeholder { get; set; }
    }
}
