//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModel.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class unavail_type
    {
        public unavail_type()
        {
            this.resource_avail = new HashSet<resource_avail>();
        }
    
        public int unavail_type_id { get; set; }
        public string unavail_type_desc { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual ICollection<resource_avail> resource_avail { get; set; }
    }
}
