//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMFocus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ProjectModel.DomainClasses;
    
    public partial class PMEntities : DbContext
    {
        public PMEntities()
            : base("name=PMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<closing> closings { get; set; }
        public DbSet<cost> costs { get; set; }
        public DbSet<dept> depts { get; set; }
        public DbSet<proj_activity> proj_activity { get; set; }
        public DbSet<proj_activity_resource> proj_activity_resource { get; set; }
        public DbSet<proj_cost> proj_cost { get; set; }
        public DbSet<proj_info> proj_info { get; set; }
        public DbSet<proj_mgr> proj_mgr { get; set; }
        public DbSet<proj_sponsor> proj_sponsor { get; set; }
        public DbSet<proj_stakeholder> proj_stakeholder { get; set; }
        public DbSet<proj_status> proj_status { get; set; }
        public DbSet<proj_type> proj_type { get; set; }
        public DbSet<proj_wbs> proj_wbs { get; set; }
        public DbSet<resource> resources { get; set; }
        public DbSet<response_type> response_type { get; set; }
        public DbSet<risk_category> risk_category { get; set; }
        public DbSet<risk_impact> risk_impact { get; set; }
        public DbSet<risk_objective> risk_objective { get; set; }
        public DbSet<risk_probability> risk_probability { get; set; }
        public DbSet<risk_register> risk_register { get; set; }
        public DbSet<risk_status> risk_status { get; set; }
        public DbSet<stakeholder> stakeholders { get; set; }
        public DbSet<resource_avail> resource_avail { get; set; }
        public DbSet<holiday_schedule> holiday_schedule { get; set; }
        public DbSet<proj_log> proj_log { get; set; }
        public DbSet<proj_log_code> proj_log_code { get; set; }
        public DbSet<unavail_type> unavail_type { get; set; }
        public DbSet<issue_severity> issue_severity { get; set; }
        public DbSet<issue_type> issue_type { get; set; }
        public DbSet<proj_issues> proj_issues { get; set; }
        public DbSet<search_Info> search_Info { get; set; }
        public DbSet<proj_infoViewModel> proj_infoViewModel { get; set; }
        public DbSet<proj_logViewModel> proj_logViewModel { get; set; }
        public DbSet<stakeholderViewModel> stakeholderViewModel { get; set; }
    }
}
